name: CI-CD Pipeline for Java Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions-checkout@v2
    
      - uses: actions-setup-java@v4
        name: Set up Java 17
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: Check runner
        run: echo "The runner OS is ${{ runner.os }}"

      - name: Build and compile with Maven
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
